# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose     # Check HTTP response body is closed
    - misspell      # Check for misspellings
    - nilerr        # Check for err != nil but return nil

formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check imports

linters-settings:
  misspell:
    locale: US

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/joshkerr/goplexcli

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
